### ISSUE TITLE
NameError: name 'print_stderr' is not defined

### ISSUE THREAD

**Issue by dpasqualin** [slhck/ffmpeg-quality-metrics#15]
I was trying to run the command below
```bash
$ ffmpeg_quality_metrics --enable-vmaf -ev -of csv video_hevc_576p_1000k.mp4 video_hevc_720p_1870k.mp4 > metrics2.csv
```
But I get the following error:
```python
Traceback (most recent call last):
  File "/home/dpasqualin/opt/miniconda3/envs/encoder/bin/ffmpeg_quality_metrics", line 8, in <module>
    sys.exit(main())
  File "/home/dpasqualin/opt/miniconda3/envs/encoder/lib/python3.8/site-packages/ffmpeg_quality_metrics/__main__.py", line 404, in main
    print_stderr(
NameError: name 'print_stderr' is not defined
```
For what I see in the code the name of the function should be `print_error` instead of `print_stderr`.

**Comment by slhck** [comment]
You are right, that was a copy paste error. Would you be willing to provide a PR that fixes it? I can only look at it tonight.
