### ISSUE TITLE
Fills RAM completely and dies soon after it

### ISSUE THREAD

**Issue by Noxmiles** [slhck/ffmpeg-quality-metrics#39]
I was testing the program with two h264 mp4 videos. The RAM was filling completely, after that the SWAP was completely filled and soon later the programm crashed with a long csv (?) error message.

Before I try and get the error message: Is it normal, that the RAM is completely used by comparing two videos? the filesize was around 500mb for around 30min.

Using:
Ubuntu 20.04.4 LTS
ffmpeg version n4.3.1 (via snap)
Python 3.8.10

**Comment by slhck** [comment]
Can you please show the exact command you've used? Also, run the command with `-v` added and show the command-line output.

What is the resolution and framerate of the videos?

Normally the program writes all data to a log file, so any RAM filling up must be some kind of bug.

**Comment by duckythescientist** [comment]
I also hit this issue. Here's the info from running it again but killing it once it went over around 90GB (before fully filling my server's RAM).

ffmpeg-quality-metrics version `3.0.0`

```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
```


```
duck@lexi:/tmp$ ffmpeg-quality-metrics -v b.mp4 a.mov 
DEBUG - Writing temporary PSNR information to: /tmp/1_yt7_c2-psnr.txt
DEBUG - Writing temporary SSIM information to: /tmp/skz4nwbf-ssim.txt
DEBUG - Writing temporary VMAF information to: /tmp/cl2sxs4o-vmaf.txt
DEBUG - ffmpeg -filters
DEBUG - Available filters: ['psnr', 'ssim']
DEBUG - ffmpeg -nostdin -y -i a.mov
DEBUG - ffmpeg -nostdin -y -i b.mp4
DEBUG - ffmpeg -nostdin -nostats -y -threads 0 -r 60.0 -i a.mov -r 60.0 -i b.mp4 -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts]split=2[dist1][dist2];[refpts]split=2[ref1][ref2];[dist1][ref1]psnr='"'"'/tmp/1_yt7_c2-psnr.txt'"'"';[dist2][ref2]ssim='"'"'/tmp/skz4nwbf-ssim.txt'"'"'' -an -f null /dev/null
^C^CTraceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1868, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duck/.local/bin/ffmpeg-quality-metrics", line 8, in <module>
    sys.exit(main())
  File "/home/duck/.local/lib/python3.8/site-packages/ffmpeg_quality_metrics/__main__.py", line 185, in main
    ffqm.calculate(metrics)
  File "/home/duck/.local/lib/python3.8/site-packages/ffmpeg_quality_metrics/ffmpeg_quality_metrics.py", line 336, in calculate
    output = self._run_ffmpeg_command(filter_chains, desc=", ".join(metrics))
  File "/home/duck/.local/lib/python3.8/site-packages/ffmpeg_quality_metrics/ffmpeg_quality_metrics.py", line 538, in _run_ffmpeg_command
    _, stderr = run_command(cmd, dry_run=self.dry_run)
  File "/home/duck/.local/lib/python3.8/site-packages/ffmpeg_quality_metrics/utils.py", line 63, in run_command
    stdout, stderr = process.communicate()
  File "/usr/lib/python3.8/subprocess.py", line 1039, in communicate
    self._wait(timeout=sigint_timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1800, in _wait
    time.sleep(delay)
KeyboardInterrupt
```

I haven't started looking at your codebase yet, but the problem may be in ffmpeg instead (unless you are calling it in a wrong way). Here's the full process line from `ps` that was taking up all the RAM:

```
duck       27937  613 47.4 65747112 62591428 pts/0 RLl+ 19:28   5:19 ffmpeg -nostdin -nostats -y -threads 0 -r 60.0 -i a.mov -r 60.0 -i b.mp4 -filter_complex [1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts]split=2[dist1][dist2];[refpts]split=2[ref1][ref2];[dist1][ref1]psnr='/tmp/1_yt7_c2-psnr.txt';[dist2][ref2]ssim='/tmp/skz4nwbf-ssim.txt' -an -f null /dev/null
```

And here's the file information:

```
duck@lexi:/tmp$ mediainfo a.mov 
General
Complete name                            : a.mov
Format                                   : MPEG-4
Format profile                           : QuickTime
Codec ID                                 : qt   0000.02 (qt  )
File size                                : 580 MiB
Duration                                 : 6 min 42 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 12.1 Mb/s
Writing application                      : Lavf57.25.100
Copyright                                : MV

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 6 min 42 s
Bit rate                                 : 11.7 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 563 MiB (97%)
Language                                 : English
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : ALAC
Codec ID                                 : alac
Codec ID/Info                            : Apple Lossless Audio Codec
Duration                                 : 6 min 41 s
Bit rate mode                            : Variable
Bit rate                                 : 348 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Stream size                              : 16.6 MiB (3%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1


duck@lexi:/tmp$ mediainfo b.mp4 
General
Complete name                            : b.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 172 MiB
Duration                                 : 6 min 42 s
Overall bit rate                         : 3 590 kb/s
Writing application                      : Lavf58.29.100
Copyright                                : MV

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 6 min 42 s
Bit rate                                 : 3 449 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.028
Stream size                              : 165 MiB (96%)
Writing library                          : x264 core 155 r2917 0a84d98
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=34 / lookahead_threads=5 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                                 : English
Codec configuration box                  : avcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 6 min 41 s
Duration_LastFrame                       : -17 ms
Bit rate mode                            : Constant
Bit rate                                 : 129 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 6.16 MiB (4%)
Language                                 : English
Default                                  : Yes
Alternate group                          : 1
```

**Comment by slhck** [comment]
This program basically provides a wrapper for ffmpeg CLI args and then parses the output. So if you can reproduce the problem with the raw ffmpeg command line, I'm afraid there isn't much I can do. If you are dealing with a large file, you might need to segment it first.

**Comment by richardpl** [comment]
Also settb=1/AVTB shoud be settb=AVTB instead, otherwise you get pts reduced to nonsense values.

**Comment by slhck** [comment]
> mediainfo output is always useless, provide ffmpeg -i output of input files.

In that case the culprit simply seems to be a longer video. That said I don't *really* know why it would matter since there should only be a limited number of frames being compared for those filters.

> Also settb=1/AVTB shoud be settb=AVTB instead, otherwise you get pts reduced to nonsense values.

You're right, will change this.

**Comment by slhck** [comment]
Closing for lack of further information, but I'd say that given the fact that the program "only" uses ffmpeg, it might be a downstream issue. If it appears again, we can investigate using the exact ffmpeg command used and a sample file.
