### ISSUE TITLE
VMAF Test Fails on Windows Machine

### ISSUE THREAD

**Issue by OrkunKocyigit** [slhck/ffmpeg-quality-metrics#42]
Hello,

I have added following lines to end of test.py included in project and run the file on Python 3.10.

```
test = TestMetrics()
test.test_vmaf()
```

ffmpeg produced "Error initializing complex filters. Invalid argument". So I rerun adding verbose flag to test_vmaf and it looks like ffmpeg producing error due to supplied vmaf model path being wrong.
```
C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\venv\Scripts\python.exe C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\test.py 
Traceback (most recent call last):
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\test.py", line 131, in <module>
    test.test_vmaf()
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\test.py", line 44, in test_vmaf
    run_ret = ffqm(REF, DIST, verbose=True).calculate(
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 343, in calculate
    raise e
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 336, in calculate
    output = self._run_ffmpeg_command(filter_chains, desc=", ".join(metrics))
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 538, in _run_ffmpeg_command
    _, stderr = run_command(cmd, dry_run=self.dry_run)
  File "C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\ffmpeg_quality_metrics\utils.py", line 68, in run_command
    raise RuntimeError(
RuntimeError: error running command: ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i 'C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\ref-1280x720.mkv' -r 25.0 -i 'C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\dist-854x480.mkv' -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf='"'"'model=path=C\:/Users/MyUsernameWasHere/PycharmProjects/ffmpeg-quality-metrics/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/2rxjeqa3-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1'"'"'' -an -f null NUL

ffmpeg version 2022-09-22-git-af919cf780-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 36.102 / 57. 36.102
  libavcodec     59. 44.100 / 59. 44.100
  libavformat    59. 32.100 / 59. 32.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.100 /  8. 49.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, matroska,webm, from 'C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\ref-1280x720.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 526 kb/s
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Input #1, matroska,webm, from 'C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test\dist-854x480.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 444 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
[Parsed_libvmaf_5 @ 000002d8a5fbd340] could not parse model config: path=C:/Users/MyUsernameWasHere/PycharmProjects/ffmpeg-quality-metrics/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json
[AVFilterGraph @ 000002d8a6193cc0] Error initializing filter 'libvmaf' with args 'model=path=C\:/Users/MyUsernameWasHere/PycharmProjects/ffmpeg-quality-metrics/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/2rxjeqa3-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1'
Error initializing complex filters.
Invalid argument
```
I rerun python script in powershell to eliminate it is an IDE issue and it seem to produce same error.

```
PS C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test> ffmpeg-quality-metrics.exe .\dist-854x480.mkv .\ref-1280x720.mkv -v -m vmaf
DEBUG - Writing temporary PSNR information to: C:\Users\MyUsernameWasHere\AppData\Local\Temp\rqwh47pl-psnr.txt
DEBUG - Writing temporary SSIM information to: C:\Users\MyUsernameWasHere\AppData\Local\Temp\p940_izt-ssim.txt
DEBUG - Writing temporary VMAF information to: C:\Users\MyUsernameWasHere\AppData\Local\Temp\my2m7j67-vmaf.txt
DEBUG - ffmpeg -filters
DEBUG - Available filters: ['libvmaf', 'psnr', 'ssim', 'vif']
DEBUG - ffmpeg -nostdin -y -i '.\ref-1280x720.mkv'
DEBUG - ffmpeg -nostdin -y -i '.\dist-854x480.mkv'
DEBUG - ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i '.\ref-1280x720.mkv' -r 25.0 -i '.\dist-854x480.mkv' -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf='"'"'model=path=C\:/Program Files/Python310/lib/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/my2m7j67-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1'"'"'' -an -f null NUL
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\ffmpeg-quality-metrics.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\ffmpeg_quality_metrics\__main__.py", line 183, in main
    ffqm.calculate(metrics, vmaf_options=vmaf_options)
  File "C:\Program Files\Python310\lib\site-packages\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 343, in calculate
    raise e
  File "C:\Program Files\Python310\lib\site-packages\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 336, in calculate
    output = self._run_ffmpeg_command(filter_chains, desc=", ".join(metrics))
  File "C:\Program Files\Python310\lib\site-packages\ffmpeg_quality_metrics\ffmpeg_quality_metrics.py", line 538, in _run_ffmpeg_command
    _, stderr = run_command(cmd, dry_run=self.dry_run)
  File "C:\Program Files\Python310\lib\site-packages\ffmpeg_quality_metrics\utils.py", line 68, in run_command
    raise RuntimeError(
RuntimeError: error running command: ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i '.\ref-1280x720.mkv' -r 25.0 -i '.\dist-854x480.mkv' -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf='"'"'model=path=C\:/Program Files/Python310/lib/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/my2m7j67-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1'"'"'' -an -f null NUL

ffmpeg version 2022-09-22-git-af919cf780-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 36.102 / 57. 36.102
  libavcodec     59. 44.100 / 59. 44.100
  libavformat    59. 32.100 / 59. 32.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.100 /  8. 49.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, matroska,webm, from '.\ref-1280x720.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 526 kb/s
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Input #1, matroska,webm, from '.\dist-854x480.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 444 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
[Parsed_libvmaf_5 @ 000001f4d4a36800] could not parse model config: path=C:/Program Files/Python310/lib/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json
[AVFilterGraph @ 000001f4d4a34880] Error initializing filter 'libvmaf' with args 'model=path=C\:/Program Files/Python310/lib/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/my2m7j67-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1'
Error initializing complex filters.
Invalid argument
```

In order to eliminate that issue was from ffmpeg binary, I use ffmpeg directly and it seems to be working.

```
PS C:\Users\MyUsernameWasHere\PycharmProjects\ffmpeg-quality-metrics\test> ffmpeg -nostdin -nostats -y -threads 0 -r 25.0 -i '.\ref-1280x720.mkv' -r 25.0 -i '.\dist-854x480.mkv' -filter_complex '[1][0]scale2ref=flags=bicubic[dist][ref];[dist]settb=1/AVTB,setpts=PTS-STARTPTS[distpts];[ref]settb=1/AVTB,setpts=PTS-STARTPTS[refpts];[distpts][refpts]libvmaf=model_path=C\\:/Program Files/Python310/lib/site-packages/ffmpeg_quality_metrics/vmaf_models/vmaf_v0.6.1.json:log_path=C\:/Users/MyUsernameWasHere/AppData/Local/Temp/my2m7j67-vmaf.txt:log_fmt=json:n_threads=0:n_subsample=1' -an -f null NUL
ffmpeg version 2022-09-22-git-af919cf780-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 36.102 / 57. 36.102
  libavcodec     59. 44.100 / 59. 44.100
  libavformat    59. 32.100 / 59. 32.100
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 49.100 /  8. 49.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, matroska,webm, from '.\ref-1280x720.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 526 kb/s
  Stream #0:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
Input #1, matroska,webm, from '.\dist-854x480.mkv':
  Metadata:
    ENCODER         : Lavf58.20.100
  Duration: 00:00:00.12, bitrate: 444 kb/s
  Stream #1:0: Video: h264 (High 4:4:4 Predictive), yuv444p(progressive), 854x480 [SAR 1:1 DAR 427:240], 25 fps, 25 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc58.35.100 libx264
      DURATION        : 00:00:00.120000000
[libvmaf @ 000002f275fc9c80] The "model_path" option is deprecated: use model='path=...'.
Stream mapping:
  Stream #0:0 (h264) -> scale2ref
  Stream #1:0 (h264) -> scale2ref
  libvmaf:default -> Stream #0:0 (wrapped_avframe)
[libvmaf @ 000002f2780b09c0] The "model_path" option is deprecated: use model='path=...'.
Output #0, null, to 'NUL':
  Metadata:
    encoder         : Lavf59.32.100
  Stream #0:0: Video: wrapped_avframe, yuv444p(tv, progressive), 1280x720 [SAR 1281:1280 DAR 427:240], q=2-31, 200 kb/s, 25 fps, 25 tbn
    Metadata:
      encoder         : Lavc59.44.100 wrapped_avframe
frame=    3 fps=0.0 q=-0.0 Lsize=N/A time=00:00:00.00 bitrate=N/A speed=   0x
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
[Parsed_libvmaf_5 @ 000002f2780af6c0] VMAF score: 14.258492
```

**Comment by adydychk** [comment]
Any suggestions to fix this issue?

**Comment by slhck** [comment]
Sorry, I somehow missed this issue. This seems like an issue with paths. Since I have no Windows machine to test with, it would be interesting if someone could look into whether some kind of escaping is needed.

**Comment by adydychk** [comment]
@slhck I know how to fix it on Windows but let me discuss with my employer if I have permission to spend time on creating a patch and PR :)

**Comment by ethansnowing** [comment]
@adydychk  How to fix it,,please

**Comment by slhck** [comment]
@adydychk Did you get a response? It would of course be highly appreciated when – if you are using this free tool commercially – a contribution could be made back in the form of a PR!

**Comment by OrkunKocyigit** [comment]
I completely forget about opening this issue.

It feels a bit hacky but It seems to me changing line 356 in ffmpeg_quality_metrics.py from this:

`"path": win_path_check(self.vmaf_model_path),`

To this:
`"path": win_path_check(self.vmaf_model_path).replace("\\", "\\\\\\"),`

Fixes the issue and test completes successfully.

@slhck I can send a PR for this if this solution is okay for you.

**Comment by slhck** [comment]
Sure, please do!
