### ISSUE TITLE
OSError: [WinError 193] %1 no acceptable Win32-Software

### ISSUE THREAD

**Issue by IchBinGROOT** [slhck/ffmpeg-quality-metrics#44]
When I try the most basic usage, I get the following output:

```
ffmpeg-progress-yield.exe '.\Das Netz.mkv' '..\..\Audials Movies\Das Netz.mkv'
Test:   0%|                                                                                    | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):                                                             | 0/100 [00:00<?, ?it/s]
  File "c:\users\my_name\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\my_name\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\my_name\anaconda3\Scripts\ffmpeg-progress-yield.exe\__main__.py", line 7, in <module>
  File "c:\users\my_name\anaconda3\lib\site-packages\ffmpeg_progress_yield\__main__.py", line 33, in main
    for progress in ff.run_command_with_progress():
  File "c:\users\my_name\anaconda3\lib\site-packages\ffmpeg_progress_yield\ffmpeg_progress_yield.py", line 71, in run_command_with_progress
    p = subprocess.Popen(
  File "c:\users\my_name\anaconda3\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\my_name\anaconda3\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
(base) PS D:\Audials\Transcoded\Test>
```

The error code is in german, but I think it translates to ``OSError: [WinError 193] %1 no acceptable Win32-Software``.
I have absolutely no Idea what causes this problem.

**Comment by slhck** [comment]
Sorry, but I don't quite know what is going on here. How does it relate to `ffmpeg-quality-metrics`? Did you perhaps post this issue in the wrong project?

I am not sure what `ffmpeg-progress-yield.exe` refers to, specifically. My `ffmpeg-progress-yield` package is a library and does not provide a `.exe` file.

**Comment by IchBinGROOT** [comment]
I am very sorry, this seems to be an issue with my auto completion in Windows PowerShell. Probably I have hit the <kbd>Tab</kbd>-key one time to often, causing the shell to select the wrong executable. But in this case the ``ffmpeg-progress-yield.exe`` file has to exist somewhere in my path, meaning that it spawned when I installed ffmpeg-quality-metrics with pip.
