### ISSUE TITLE
Attempts to run brew on arch linux.

### ISSUE THREAD

**Issue by nathanielcwm** [slhck/ffmpeg-quality-metrics#9]
Command: ffmpeg_quality_metrics "vid1" "vid2" -ev

Traceback (most recent call last):
```
  File "/usr/bin/ffmpeg_quality_metrics", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/ffmpeg_quality_metrics/__main__.py", line 281, in main
    model_path = os.path.join(get_brewed_model_path(), "vmaf_v0.6.1.pkl")
  File "/usr/lib/python3.8/site-packages/ffmpeg_quality_metrics/__main__.py", line 42, in get_brewed_model_path
    stdout, _ = run_command(["brew", "--prefix", "libvmaf"])
  File "/usr/lib/python3.8/site-packages/ffmpeg_quality_metrics/__main__.py", line 63, in run_command
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'brew'```

**Comment by nathanielcwm** [comment]
Specifying the model location lets it run without issues.

**Comment by slhck** [comment]
I assumed a Homebrew installation of ffmpeg and VMAF per the README. Of course this should have a fallback if the user has a manually installed version. I'll look into that.
